### ISSUE TITLE
split pass  don't effect

### ISSUE THREAD

**Issue by piaoapiao** [0x3f97/ollvm-12.x#1]
mac bigSur 11.4 ,llvm12
test paramter： -mllvm -split -mllvm -split_num=3

**Comment by piaoapiao** [comment]
mac bigSur 11.4 ,llvm12 
test paramter： -mllvm -split -mllvm -split_num=3

**Comment by 0x3f97** [comment]
Only tested on windows

**Comment by 0x3f97** [comment]
-mllvm -split is enough
