### ISSUE TITLE
修改代码时有个疑惑？

### ISSUE THREAD

**Issue by woshildh** [0x3f97/ollvm-12.x#3]
![image](https://user-images.githubusercontent.com/30169705/136939714-106feb7b-f8ae-4866-8be4-29af2e523fdd.png)

请问这个 `case 1: op2 = UnaryOperator::CreateFNeg(i->getOperand(0),*var,&*i);` 代码时需要复制两次的吗？虽然代码会重复执行？

**Comment by 0x3f97** [comment]
写错了
